---
title: "viz_and_eda"
author: "Jason Wang"
date: "9/26/2019"
output: github_document
---

```{r, echo = FALSE}
library(tidyverse)
install.packages("ggplot2")
install.packages("ggridges")
library(ggridges)

```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10)

 weather_df_data_set = select(weather_df, name, id, everything())
weather_df_data_set

ggplot(weather_df_data_set, aes(x = tmin, y = tmax)) + 
  geom_point()

```


```{r, }
plot_weather = 
  weather_df_data_set %>%
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()

```


```{r}
ggplot(weather_df_data_set, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))

```


why do "aes" position matter?

```{r}
ggplot(weather_df_data_set, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)

ggplot(weather_df_data_set, aes(x = tmin, y = tmax, color = name)) + 
  geom_point() +
  geom_smooth(se = FALSE)

```

facet!


```{r}
ggplot(weather_df_data_set, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)

ggplot(weather_df_data_set, aes(x = tmin, y = tmax, color = name)) + 
  geom_point() +
  geom_smooth(se = FALSE) +
  facet_grid(~name)

```

```{r}
weather_df_data_set %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE)

weather_df_data_set %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp)) +
  geom_smooth(se = FALSE)

```

### some extra stuff

```{r}
ggplot(weather_df_data_set, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(size = 2, se = FALSE) 

ggplot(weather_df_data_set, aes(x = date, y = tmax)) + 
  geom_bin2d()

weather_df_data_set %>% 
  ggplot(aes(x = tmax, color = name)) +
  geom_histogram()

weather_df_data_set %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram()

weather_df_data_set %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram(position = "dodge")

weather_df_data_set %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3)

```


```{r}
weather_df_data_set %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

weather_df_data_set %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()

```

ridge plots

```{r}
weather_df_data_set %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges(scale = .85)


```


### sacing a plot

```{r}
ggp_ridge_temp = 
  weather_df_data_set %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges(scale = .85)

ggsave("ggp_ridge_temp.pdf", ggp_ridge_temp)
```



```{r}


```

